# Generated by Django 4.0.5 on 2022-09-18 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grave_lot_id', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grave_area', models.CharField(max_length=64)),
                ('assignarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign', to='search.lotnumber')),
            ],
        ),
        migrations.CreateModel(
            name='DeceasedInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('born', models.DateField(blank=True)),
                ('died', models.DateField(blank=True)),
                ('graveimage', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravelocation', to='search.location')),
                ('lotnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotnumber', to='search.lotnumber')),
            ],
        ),
    ]
