# Generated by Django 4.0.5 on 2022-09-18 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grave_area', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='deceasedinformation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravelocation', to='search.lotname'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
