# Generated by Django 4.0.5 on 2022-09-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_lotname_alter_deceasedinformation_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceasedinformation',
            name='graveimage',
            field=models.FileField(blank=True, null=True, upload_to='Images/'),
        ),
    ]
