# Generated by Django 4.0.5 on 2022-10-22 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_alter_deceasedinformation_reference_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grave_lot_id', models.CharField(max_length=2)),
                ('grave_area', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='deceasedinformation',
            name='lotnumber',
        ),
        migrations.DeleteModel(
            name='LotNumber',
        ),
        migrations.AlterField(
            model_name='deceasedinformation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravelocation', to='search.location'),
        ),
    ]
