# Generated by Django 4.0.5 on 2022-11-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_location_remove_deceasedinformation_lotnumber_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LotName',
        ),
        migrations.AddField(
            model_name='deceasedinformation',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='location',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
