# Generated by Django 4.0.5 on 2022-11-24 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import procurement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0010_delete_lotname_deceasedinformation_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('Lot_Photo', models.ImageField(blank=True, null=True, upload_to='lot_photo')),
                ('Lot_Name', models.CharField(max_length=64)),
                ('Lot_Descriptions', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GardenDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('Lot_Image', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('Garden_Description', models.TextField(blank=True, max_length=255, null=True)),
                ('Available_Space', models.IntegerField(blank=True, default=0)),
                ('Date_Modified', models.DateTimeField(auto_now=True)),
                ('Garden_Name', models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gardenname', to='search.location')),
                ('Lot_Type', models.ManyToManyField(to='procurement.lottype')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(default=procurement.models.ref, editable=False, max_length=20)),
                ('first_Name', models.CharField(max_length=64, null=True)),
                ('last_Name', models.CharField(max_length=64, null=True)),
                ('contact_Number', models.CharField(max_length=64, null=True)),
                ('deceased_Name', models.CharField(max_length=64, null=True)),
                ('born_Date', models.DateField(null=True)),
                ('died_Date', models.DateField(null=True)),
                ('burial_Schedule', models.DateField(null=True)),
                ('status', models.BooleanField(choices=[(True, 'Processed'), (False, 'Not Processed')], default=False)),
                ('chosen_Lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chosenLot', to='procurement.gardendetail')),
                ('chosen_Lot_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chosenLotType', to='procurement.lottype')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
